version: '3.8'

services:
  portfolio:
    build: .
    container_name: portfolio
    restart: unless-stopped
    labels:
      # Labels do Traefik
      - "traefik.enable=true"
      - "traefik.docker.network=simulador_traefik_network"
      
      # Porta HTTP
      - "traefik.http.routers.portfolio-http.rule=Host(`devgabrieldias.agentelegtech.pro`)"
      - "traefik.http.routers.portfolio-http.entrypoints=web"
      - "traefik.http.routers.portfolio-http.middlewares=redirect-to-https"
      
      # Porta HTTPS
      - "traefik.http.routers.portfolio.rule=Host(`devgabrieldias.agentelegtech.pro`)"
      - "traefik.http.routers.portfolio.entrypoints=websecure"
      - "traefik.http.routers.portfolio.tls.certresolver=letsencryptresolver"
      - "traefik.http.services.portfolio.loadbalancer.server.port=80"
      
      # Middleware para redirecionar HTTP para HTTPS
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
    
    networks:
      - portfolio_network
      - simulador_traefik_network

networks:
  portfolio_network:
    driver: bridge
  simulador_traefik_network:
    external: true

